
; ==============================================================
; --------------------------------------------------------------
; Mega PCM 2.0
;
; DPCM Delta conversion tables
; --------------------------------------------------------------
; WARNING! This file was auto-generated by `mkdpcmtbl`.
; --------------------------------------------------------------
; (c) 2023, Vladikcomper
; --------------------------------------------------------------

	; Nibble 0 conversion table
	db	000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h,000h
	db	001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,001h,001h
	db	002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,002h,002h
	db	004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h,004h
	db	008h,008h,008h,008h,008h,008h,008h,008h,008h,008h,008h,008h,008h,008h,008h,008h
	db	010h,010h,010h,010h,010h,010h,010h,010h,010h,010h,010h,010h,010h,010h,010h,010h
	db	020h,020h,020h,020h,020h,020h,020h,020h,020h,020h,020h,020h,020h,020h,020h,020h
	db	040h,040h,040h,040h,040h,040h,040h,040h,040h,040h,040h,040h,040h,040h,040h,040h
	db	080h,080h,080h,080h,080h,080h,080h,080h,080h,080h,080h,080h,080h,080h,080h,080h
	db	0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
	db	0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh,0FEh
	db	0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh,0FCh
	db	0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h,0F8h
	db	0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h,0F0h
	db	0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h,0E0h
	db	0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h,0C0h

	; Nibble 1 conversion table
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
	db	000h,001h,002h,004h,008h,010h,020h,040h,080h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h

